### PR TITLE
Major changes in many places

### PR DESCRIPTION
**Pull request by Lukc**
This PR is mostly to get your opinion about these changes. Considering the documentation doesn’t match the actual code anymore, I’m pretty sure this PR cannot be accepted without some additional work.

Anyway, here’s a list of the things I changed and I can remember:

  - lunadoc’s module has been split into smaller components.
    - Document, Project and Template are the three new classes that obtained most of the code from lunadoc.init.
    - They’re sort-of designed to be usable from the outside to a certain extend. In their current form, they should be easy to test. (I was too lazy to write tests though. It’s late, I’m tired.)
  - lunadoc.moon’s a CLI for lunadoc’s module.
    - It uses argparse.
    - It allows changing the template, extension of doc files, and the output directory.
  - I imported the DSL from Lapis to have another template engine. I noticed you had one in dysnomia a bit later, and I think it would be better to use that one if possible. Again, too lazy to roll back and make the switch.
  - It’s possible to change the extension/suffix of things that are built.
  - I added a Makefile from a pseudo-build-system I wrote. Right now things are a bit like a “build system zoo”, so I it would be best to remove it (or the older one, you decide).
  - The content of the previous pull request is included in this one.
  - I probably broke tooons of stuff. It might make testing difficult. I apologize in advance if that’s the case. :(

### CODE REVIEW

**Comment by nonchip** [comment]
lunadoc isn't even at the point where i consider it 1.0 stable and you take the liberty to rewrite my whole project? thanks but no thanks.

**Comment by nonchip** [comment]
i mean seriously, that's not "many changes in many places", that's rewriting everything breaking every compatibility and the mere point of the project so far. especially with that 300 lines makefile hell you decided was a good idea even though there was already a build system in place

**Comment by nonchip** [comment]
also for some reason you decided to silently switch not only the lua version but also implementation.

**Comment by nonchip** [comment]
i started lunadoc because i wanted my own, working, the way i expect it, documentation generator, not because i wanted it taken out of my hands by someone who isn't even sure they want to use it.

**Comment by nonchip** [comment]
it's MIT, so if you want that aberration of a fork you did there, just change your project name and have fun. but nobody can expect rewriting the whole fucking project and just dropping a PR without even asking if we want help or if that even remotely touches what we might envision with the project would do any good.

**Comment by Lukc** [comment]
Yeah, I agree it pretty much is a rewrite of most of the project.

Please don’t take it wrong, I never expected it to be merged, even less as it is. =/

But at least *I* have a need for some of the features implemented in there, and LDoc is… well, you know how it is. I’m more interested in what you’ll implement and how it’ll work than by having my own code merged in, but I’d sure like to discuss what *will* be implemented.

Regards,

**Comment by nonchip** [comment]
yeah then maybe you should have used an issue to talk about features you'd like, because i'm not gonna read and understand what you've done to my code if you could instead of abusing it that badly have just written 3 sentences.

and now excuse me please, i ran out of cigarettes and need to recover from that shock.

**Pull request closed without merging**
